# Generated by Django 5.2.7 on 2025-10-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('context', models.TextField(help_text='Describe tu proyecto educativo, objetivos, contenido, etc.', verbose_name='Contexto del Proyecto')),
                ('limitations', models.TextField(help_text='Recursos limitados, tiempo, nivel de estudiantes, etc.', verbose_name='Tus Limitaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
